### ISSUE TITLE
Resetting Wemos

### ISSUE THREAD

**Issue by CerielRoland** [albetaCOM/esp-haier#1]
Hi there,

After following your configuration files I compiled the .bin and flashed it to several Wemos D1 mini's.
All are rebooting and exiting with errors:

[14:12:18]s$
[14:12:31][C][
[14:12:31] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
[14:12:31]
[14:12:31]load 0x4010f000, len 1384, room 16 
[14:12:31]tail 8
[14:12:31]chksum 0x2d
[14:12:31]csum 0x2d
[14:12:31]v8b899c12
[14:12:31]~ld
[14:12:31][I][logger:156]: Log initialized

Any advise?
Same if we only power the unit without log.

**Comment by CerielRoland** [comment]
Found the issue:
`#  baud_rate: 0 #Important. You can't use serial port`
needs to be without the first #.

**Comment by albetaCOM** [comment]
Hi Ceriel, 

Sorry for the late reply. Great the you are able to work with the file. I update the yaml file to be the same it is working with my devices.

Take into account that I've been doing some changes on the Haier.h to be able to work with the Haier modes. Probably the one that you have is not updated.
