### ISSUE TITLE
Lost ability to turn the AC off

### ISSUE THREAD

**Issue by megachammer** [albetaCOM/esp-haier#11]
With last update the power-off button disappeared. Could you check it?
![image](https://user-images.githubusercontent.com/19786428/135088174-baee36c9-fbde-4478-a60b-b40f86a61ddf.png)

**Comment by megachammer** [comment]
[Haierv2-1.zip](https://github.com/albetaCOM/esp-haier/files/7791532/Haierv2-1.zip)
Fixed

**Comment by albetaCOM** [comment]
Solved on commit d5e9bd6


Many thanks!!
