### ISSUE TITLE
outside temperature showing as current

### ISSUE THREAD

**Issue by evlo** [albetaCOM/esp-haier#14]
Hi,

today i just started with testing esphome etc. with goal to get away form hON and smartAir2 (as I even have both, grrr)

Anyways, this is from my AC flexisPlus "V3", "V4" is one with hON connection

current temperature in log is actually outside temperature, current would be 22C and mode HEAT_COOL should be DRY, dunno what is up with that, fan mode is auto etc. I guess maybe haierv2 would be correct in my case?
https://i.imgur.com/7g1X3Vz.png

I will create pull request if i'm able to create file that will work with AC I have.

Not nice of haier to change protocol, seemingly for each unit and not even documenting it.

**Comment by albetaCOM** [comment]
Hi! Sorry I've been out for so long.

What do you mean by outside temperature vs current temperature? My unit only reports 2 temperatures that I know of: target temperature (the temperature that I want) and current temperature (the temperature that the unit is sensing)

**Comment by evlo** [comment]
hOn ones do report outside with offset, that got me confussed, i Guess, it is long time ago. Smartair oběd indeed report only current And target.

 all Is ok now
