### ISSUE TITLE
Pull Futures from Oksion/esphaier fork

### ISSUE THREAD

**Issue by AdamN1** [albetaCOM/esp-haier#2]
Hi,
Couple of futures like fan control is merged in the fork https://github.com/Oksion/esphaier, like:

- support fan mode and swing mode
- fan speed for fan only mode
- silent mode. (silent - low mode, 1 -medium 2-middle 3-high)

**Comment by albetaCOM** [comment]
Thanks Adam!

I'll take a loop and import the changes!

**Comment by AdamN1** [comment]
After adding new function README should be changed.

**Comment by albetaCOM** [comment]
Adam

**Comment by albetaCOM** [comment]
Hi Adam, I imported locally the changes but I get many errors related to the esphome climate traits:
src/Haierv2.h:168:16: error: 'class esphome::climate::ClimateTraits' has no member named 'set_supports_dry_mode'
         traits.set_supports_dry_mode(true);
                ^
src/Haierv2.h:169:16: error: 'class esphome::climate::ClimateTraits' has no member named 'set_supports_fan_only_mode'
         traits.set_supports_fan_only_mode(true);
                ^
src/Haierv2.h:170:16: error: 'class esphome::climate::ClimateTraits' has no member named 'set_supports_fan_mode_on'
         traits.set_supports_fan_mode_on(false);
                ^
src/Haierv2.h:171:16: error: 'class esphome::climate::ClimateTraits' has no member named 'set_supports_fan_mode_off'
         traits.set_supports_fan_mode_off(false);
                ^
src/Haierv2.h:172:16: error: 'class esphome::climate::ClimateTraits' has no member named 'set_supports_fan_mode_auto'
         traits.set_supports_fan_mode_auto(true);

Do you have a different version of ESPHome that already support those traits?

**Comment by albetaCOM** [comment]
I've changed to ESPHome developer version v1.15.0b4 and it is working now. Thanks!

In the next days I'll try to adapt every new feature so it works with everything available.

**Comment by AdamN1** [comment]
Sorry fo delay, yes you need beta (15) version of esphome.
