### ISSUE TITLE
Haier ac ies not working 

### ISSUE THREAD

**Issue by 27andrea** [albetaCOM/esp-haier#4]
Hi, i have Tried to configure esphome with haier or haierv2 but it doesn't work.
I don't receive any errors on log.
I Tried to invert tx/rx on wemos with no luck.
I use haier ies that use the usb kzw-w002 
Thanks

**Comment by albetaCOM** [comment]
Can you post a picture of your set up? Were you able to flash the firmware to the wemo?

**Comment by albetaCOM** [comment]
Due to the lack of answer
