### ISSUE TITLE
Esphome 1.19.1 breaking changes 

### ISSUE THREAD

**Issue by megachammer** [albetaCOM/esp-haier#9]
Esphome 1.19.1 have a breaking changes in climate component https://github.com/esphome/esphome/pull/1933
Could you please update your firmware to support it?

**Comment by megachammer** [comment]
https://github.com/MiguelAngelLV/esphaier has workign version of .h for old versions от AC. Check it please

**Comment by albetaCOM** [comment]
Hi @megachammer, sorry, I've been out several months now.

I'll take a look and update it, thanks

**Comment by albetaCOM** [comment]
Already updated, thanks!

**Comment by megachammer** [comment]
After the last update I have lost the ability to control fan speed. Could you check it please?
![image](https://user-images.githubusercontent.com/19786428/135084395-e709c7ef-21c1-4699-8322-284240031c54.png)
